name: Demo
on:
  pull_request:
permissions:
  pull-requests: write

# Ensure only one demo runs at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  demo:
    name: Demo Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Manage Demo
        uses: ./.github/actions/demo-service
        with:
          charm-root: ./charm
